### ISSUE TITLE
Add support for multiple DS18B20 temperature sensors

### ISSUE THREAD

**Issue by maximweb** [brewpeople/brewslave#21]
In order to allow different sized pullups, I intent to add the temperature sensors to individual pins. I saw at least one example (but using a different DallasTemperature lib) where it worked.

In `configure` / `config.ini` we could add multiple sections eg. `[ds18b20-1]`, `[ds18b20-2]` etc. defining different pins. Would this work with the mock sensor (eg. only one sensor connected, the other as mock controller)? In lack of sensors, I have not tried yet. @matze any ideas or preferences?

- [x] add support for two temperature sensors on different pins -> e88c2b67bd507e739ed06cf28d83ff0c66744613
- [x] make sensors hot-swappable (already the case)
- [ ] add all sensors to communication protocol

In the old setup, I implemented two additional features we should consider:
- [x]  keep track of when the sensor was last successfully read -> otherwise it's possible that we only see old data, if there are connection troubles
- [x] If sensor readout was not successful, try to reconnect / scan. I'm not sure if it's plug-and-measure at the moment.
- [x] allow parasite mode

**Comment by matze** [comment]
> In configure / config.ini we could add multiple sections eg. [ds18b20-1], [ds18b20-2] etc. defining different pins.

We should give them actual semantics otherwise we cannot tell on a higher level which is which. Since this it is unlikely we will ever use anything else than DS18B20, they can just be `[brew-sensor]` and `[ambient-sensor]`. And sure, depending on the configuration we can instantiate zero, one or two mock sensors.

Are you working on this or should I make a proposal? (Hint: we could use the fancy issue assignment feature :wink:)

**Comment by matze** [comment]
Two things before I go into more details tonight: 1) reviewing and commenting is easier if this is a PR not just a branch, 2) please use formatting/naming like everything else, the braces and lowerCamelCase look funky to me.
